version: '3'

services:
  app: 
    build: C:\Users\Karo\Desktop\Bot  
  postgres:
    ports:
      - "5432:5432"
    environment:  
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bot_users
    image: postgres
  redis:
    ports:
      - "6379:6379"
    image: redis
